import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/UserContext";
import AuthGuard from "./components/Auth/AuthGuard";
import React from "react";
import { Appbar } from "./components/Appbar/Appbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ height: "100vh" }}>
        <UserProvider>
          <AuthGuard>
            <Appbar />
            {children}
          </AuthGuard>
        </UserProvider>
      </body>
    </html>
  );
}
